package br.com.sicoob.icg.processamento.negocio.enums;

public enum ConstantePessoaFisicaEnum {
	
	QTD_CAMPOS_OBRIGATORIOS (25),
	TAMANHO_CPF (11),
	TAMANHO_BOLMENOREMANCIPADO (1),
	TAMANHO_NOMEMAE (100),
	TAMANHO_NOMEPAI (100),
	TAMANHO_CODTIPODOCUMENTOIDENTIFICACAO (1),
	TAMANHO_NUMDOCUMENTOIDENTIFICACAO (30),
	TAMANHO_ORGAOEXPEDIDORDOCUMETO (20),
	TAMANHO_UFORGEXPDOCUMENTOIDENTIFICACAO (2),
	TAMANHO_CODTIPOSEXO (1),
	TAMANHO_BOLUNIAOESTAVEL (1),
	TAMANHO_CODESTADOCIVIL (1),
	TAMANHO_CODNACIONALIDADE (5),
	TAMANHO_DESCNATURALIDADE (40),
	TAMANHO_CODIGO_NATURALIDADE (10),
	TAMANHO_CODVINCULOEMPREGATICIO (5),
	TAMANHO_IDOCUPACAOPROFISSIONAL (5),
	TAMANHO_CODGRAUINSTRUCAO (5),
	TAMANHO_QTDDEPENDENTE (5),
	TAMANHO_CODREGIMECASAMENTO (5),
	TAMANHO_NOMEPESSOA (60),
	TAMANHO_NOMECOMPLETO (100),
	TAMANHO_CAMPO_DATA (10),
	
	POSICAO_CAMPO_CPF (0),
	POSICAO_CAMPO_NOMEPESSOA (1),
	POSICAO_CAMPO_NOMECOMPLETO (2),
	POSICAO_CAMPO_DATANASCIMENTO (3),
	POSICAO_CAMPO_CODATIVIDADEECONOMICA (4),
	POSICAO_CAMPO_BOLMENOREMANCIPADO (5),
	POSICAO_CAMPO_NOMEMAE (6),
	POSICAO_CAMPO_NOMEPAI (7),
	POSICAO_CAMPO_CODTIPODOCUMENTOIDENTIFICACAO (8),
	POSICAO_CAMPO_NUMDOCUMENTOIDENTIFICACAO (9),
	POSICAO_CAMPO_ORGAOEXPEDIDORDOCUMETO (10),
	POSICAO_CAMPO_SIGLAUFORGEXPDOCUMENTOIDENTIFICACAO (11),
	POSICAO_CAMPO_DATAEMISSAODOCUMENTO (12),
	POSICAO_CAMPO_CODTIPOSEXO (13),
	POSICAO_CAMPO_BOLUNIAOESTAVEL (14),
	POSICAO_CAMPO_CODESTADOCIVIL (15),
	POSICAO_CAMPO_DESCNATURALIDADE (16),
	POSICAO_CAMPO_CODIGO_NATURALIDADE (17),
	POSICAO_CAMPO_CODVINCULOEMPREGATICIO (18),
	POSICAO_CAMPO_IDOCUPACAOPROFISSIONAL (19),
	POSICAO_CAMPO_CODGRAUINSTRUCAO (20),
	POSICAO_CAMPO_QTDDEPENDENTE (21),
	POSICAO_CAMPO_CPFCONJUGE (22),
	POSICAO_CAMPO_CODREGIMECASAMENTO (23),
	POSICAO_CAMPO_CODNACIONALIDADE(24);

	private Integer codigo;

	private ConstantePessoaFisicaEnum(Integer codigo) {
		this.codigo = codigo;
	}

	public Integer getCodigo() {
		return codigo;
	}

	public static ConstantePessoaFisicaEnum obterPorCodigo(Integer codigo) {
		for (ConstantePessoaFisicaEnum constanteEnderecoEnum : values()) {
			if (constanteEnderecoEnum.codigo.equals(codigo)) {
				return constanteEnderecoEnum;
			}
		}
		return null;
	}

}